name: Build Client

on:
  push:
    branches: [ 'master' ]
  pull_request:
    branches: [ 'master' ]

jobs:
  cancel-previous:
    name: 'Cancel Previous Runs'
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}

  build:
    runs-on: ubuntu-latest
    needs: cancel-previous
    env:
      APP_DIR: $HOME/work/iam-client-examples/iam-client-examples/client
    strategy:
      matrix:
        DAPPS: [angular-dapp, react-dapp, vue-dapp]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'

      - name: Build dapp
        run: |
          cd ${{ env.APP_DIR }}/${{ matrix.DAPPS }}
          npm ci
          npm run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        # if: github.ref == 'refs/heads/master'
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          SOURCE: "./"
          REMOTE_HOST: ${{ secrets.SERVER_HOST }}
          REMOTE_USER: ${{ secrets.SERVER_USER }}
          TARGET: ${{ env.APP_DIR }}/${{ matrix.DAPPS }}
