name: Build Client

on:
  push:
    branches: [ 'master', 'DOI-887_iam_client_example_to_GH' ]
  pull_request:
    branches: [ 'master' ]

jobs:
  cancel-previous:
    name: 'Cancel Previous Runs'
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}

  build:
    runs-on: ubuntu-latest
    needs: cancel-previous
    env:
      APP_DIR: $HOME/work/iam-client-examples/iam-client-examples/client
    strategy:
      matrix:
        DAPPS: [angular-dapp, react-dapp, vue-dapp]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'

      - name: Build dapp
        run: |
          cd ${{ env.APP_DIR }}/${{ matrix.DAPPS }}
          npm ci
          npm run build

      - name: Deploy client on instance
        uses: trendyminds/github-actions-rsync@master
        with:
          RSYNC_OPTIONS: -rv
          RSYNC_SOURCE: ${{ env.APP_DIR }}/${{ matrix.DAPPS }}
          RSYNC_TARGET: ~/iam-client-examples/${{ matrix.DAPPS }}
        env:
          SSH_HOSTNAME: ${{ secrets.SERVER_HOST }}
          SSH_USERNAME: ${{ secrets.SERVER_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_KEY }}
