name: Deploy

on:
  push:
    branches: [ 'master', 'DOI-887_iam_client_example_to_GH' ]
  pull_request:
    branches: [ 'master' ]

jobs:
  cancel-previous:
    name: 'Cancel Previous Runs'
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}

  deploy:
    runs-on: ubuntu-latest
    needs: cancel-previous
    env:
      SERVER_DIR: ~/iam-client-examples/server
      APP_DIR: ~/iam-client-examples/client
    strategy:
      matrix:
        DAPPS: [angular-dapp, react-dapp, vue-dapp]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'

      - name: Deploy client on instance
        uses: burnett01/rsync-deployments@5.0
        with:
          switches: -rv
          path: dist/*
          remote_path: ${{ env.SERVER_DIR }}/{{ env.APP_DIR }}/${{ matrix.DAPPS }}
          remote_host: ${{ secrets.SERVER_HOST }}
          remote_user: ${{ secrets.SERVER_USER }}
          remote_key: ${{ secrets.SERVER_KEY }}

      - name: Deploy server on instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd ${{ env.SERVER_DIR }}/express
            sh ./deploy.sh
            npm install
            npm run
